spring:
  datasource:
    url: jdbc:postgresql://db.tqtcapligrwbsbtgimsu.supabase.co:5432/postgres
    username: postgres # root에서 postgres로 수정
    password: Q!w2e3r4t5y6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # 이 줄을 추가하면 더 안전합니다
        format_sql: true

  thymeleaf:
    cache: false
    check-template-location: true